### ISSUE TITLE
[Suggestion] Update idf_component.yml in all examples to use idf version: ">=5.2.1" and esp-zboss-lib + esp-zigbee-lib "~1.2.1" (TZ-717)

### ISSUE THREAD

**Issue by Hedda** [espressif/esp-zigbee-sdk#299]
### Is your feature request related to a problem?

Development of esp-zigbee-sdk + esp-zboss-lib + esp-zigbee-lib is moving fast so examples work much better with later versions.

Suggest update to latest idf component in all examples, so use idf version: ">=5.2.1" and esp-zboss-lib + esp-zigbee-lib "~1.2.1"

https://github.com/espressif/esp-zigbee-sdk/tree/main/examples

https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_HA_sample

For example ;

https://github.com/espressif/esp-zigbee-sdk/blob/main/examples/esp_zigbee_HA_sample/HA_on_off_light/main/idf_component.yml

```
## IDF Component Manager Manifest File
dependencies:
  espressif/esp-zboss-lib: "~1.2.1"
  espressif/esp-zigbee-lib: "~1.2.1"
  espressif/led_strip: "~2.0.0"
  ## Required IDF version
  idf:
    version: ">=5.2.1"
```

### Describe the solution you'd like.

Update all the examples to use later min versions of idf, esp-zboss-lib, and esp-zigbee-lib compared to what they are using now.
