### ISSUE TITLE
How to handle leave request from coordinator? (TZ-133)

### ISSUE THREAD

**Issue by Tropaion** [espressif/esp-zigbee-sdk#30]
Hello, me again :D

I'm trying to handle the case when the coordinator sends a leave request to my end device.
I managed to find out that there isn't a explicit signal for it but the signal ```ESP_ZB_ZDO_SIGNAL_LEAVE``` is triggered.
But it looks like there isn't a fitting leave type or other parameter defined for this case.
When I try to read the leave type in this case, I get the value "306905088".
Is there another way to identify this case?

**Comment by xieqinan** [comment]
Hello @Tropaion ,
Can you tell me the commit ID for your esp-zigbee-sdk? The `leave_type` value has been fixed in commit `503dce9f2`.

**Comment by Tropaion** [comment]
How do I get the commit ID? I'm using the VS Code Plugin.

**Comment by xieqinan** [comment]
You can modify the `idf_component.yml` file to obtain the latest versions of `esp-zigbee-lib` and `esp-zboss-lib`, which can be found in the main folder of every example. The most recent version, as of May 31, 2023, is as follows:

```
## IDF Component Manager Manifest File
dependencies:
  espressif/esp-zboss-lib: "~0.5.0"
  espressif/esp-zigbee-lib: "~0.6.0"
  ## Required IDF version
  idf:
    version: ">=5.0.0"

```

**Comment by Tropaion** [comment]
@xieqinan Thanks, I suspected something like that.
I tried to look into what the ```~``` is for, but didn't find anything in docu so I changed my file to:
```
## IDF Component Manager Manifest File
dependencies:
  espressif/esp-zigbee-lib: ">=0.5.0"
  espressif/esp-zboss-lib: ">=0.3.0"
  espressif/button: ">=2.5.1"
  ## Required IDF version
  idf:
    version: ">=5.0.0"
```
I thought with this it automatically always uses the newest version, but appearently it does not.
Is there a way to do this?
